In [47]:
import numpy as np
import gymnasium as gym

In [49]:
env = gym.make("FrozenLake-v1", is_slippery=False)

print("States :", env.observation_space.n)
print("Actions :", env.action_space.n)

States : 16
Actions : 4


In [51]:
q_table = np.zeros((16, 4))

print(q_table)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [53]:
#hyperparameters for rl
learning_rate = 0.8 #defining the right step to agent
gamma = 0.95 #how much you want your agent to explore 

epsilon = 1.0 #how much it explored 
epsilon_decay = 0.999
epsilon_min = 0.01

episodes = 20000 # 2000 times agent go from start to end 

In [55]:
for episode in range(episodes):

    state, _ = env.reset()

    done = False

    while not done:

        # Epsilon-Greedy
        if np.random.uniform(0,1) < epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])

        next_state, reward, terminated, truncated, _ = env.step(action)

        done = terminated or truncated

        # Q-Learning Formula
        q_table[state, action] = q_table[state, action] + learning_rate * (
            reward + gamma * np.max(q_table[next_state]) - q_table[state, action]
        )

        state = next_state

    if epsilon > epsilon_min:
        epsilon *= epsilon_decay

In [56]:
print(q_table)

[[0.73509189 0.77378094 0.77378094 0.73509189]
 [0.73509189 0.         0.81450625 0.77378094]
 [0.77378094 0.857375   0.77378094 0.81450625]
 [0.81450625 0.         0.77378094 0.77378094]
 [0.77378094 0.81450625 0.         0.73509189]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.         0.81450625]
 [0.         0.         0.         0.        ]
 [0.81450625 0.         0.857375   0.77378094]
 [0.81450625 0.9025     0.9025     0.        ]
 [0.857375   0.95       0.         0.857375  ]
 [0.         0.         0.         0.        ]
 [0.         0.         0.         0.        ]
 [0.         0.9025     0.95       0.857375  ]
 [0.9025     0.95       1.         0.9025    ]
 [0.         0.         0.         0.        ]]


In [57]:
state, _ = env.reset()

done = False

total_reward = 0

while not done:

    action = np.argmax(q_table[state])

    next_state, reward, terminated, truncated, _ = env.step(action)

    done = terminated or truncated

    total_reward += reward

    state = next_state

print("Reward :", total_reward)

Reward : 1


In [58]:
state = 0

best_action = np.argmax(q_table[state])

print("Best Action :", best_action)

Best Action : 1
